---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: qbittorrent
  namespace: qbittorrent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: qbittorrent
  template:
    metadata:
      labels:
        app: qbittorrent
    spec:
      containers:

        ######################################################
        # 🔵 Gluetun (VPN Sidecar)
        ######################################################
        - name: gluetun
          image: qmcgaw/gluetun
          securityContext:
            capabilities:
              add:
                - NET_ADMIN
          env:
            - name: VPN_SERVICE_PROVIDER
              value: "protonvpn"
            - name: VPN_TYPE
              value: "wireguard"
            - name: WIREGUARD_PRIVATE_KEY
              valueFrom:
                secretKeyRef:
                  name: qbittorrent-secrets
                  key: vpn-token
            - name: SERVER_COUNTRIES
              value: "United Kingdom"
            - name: SERVER_CITIES
              value: "London"
            - name: VPN_PORT_FORWARDING
              value: "on"
            - name: HTTP_CONTROL_SERVER_AUTH_DEFAULT_ROLE
              value: '{"auth":"none"}'
          volumeMounts:
            - name: dev-net-tun
              mountPath: /dev/net/tun
            - name: gluetun-config
              mountPath: /gluetun

        ######################################################
        # 🟡 qBittorrent (Client)
        ######################################################
        - name: qbittorrent
          image: linuxserver/qbittorrent:5.1.2
          ports:
            - name: http
              containerPort: 8080
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "100"
            - name: WEBUI_PORT
              value: "8080"

            # Força o qBittorrent a usar a interface do Gluetun
            - name: QBITTORRENT_INTERFACE
              value: "tun0"

            # Mod para sync de port forwarding
            - name: DOCKER_MODS
              value: "ghcr.io/t-anc/gsp-qbittorent-gluetun-sync-port-mod:main"
            - name: GSP_SKIP_INIT_CHECKS
              value: "warning"
            - name: GSP_MINIMAL_LOGS
              value: "false"
            - name: GSP_QBT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: qbittorrent-secrets
                  key: qbittorrent-user
            - name: GSP_QBT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: qbittorrent-secrets
                  key: qbittorrent-password
            - name: GSP_GTN_ADDR
              value: "http://localhost:8000"

          volumeMounts:
            - name: config
              mountPath: /config
            - name: downloads
              mountPath: /downloads
            - name: files
              mountPath: /files
            - name: output
              mountPath: /output

      ######################################################
      # Volumes
      ######################################################
      volumes:
        - name: dev-net-tun
          hostPath:
            path: /dev/net/tun
            type: CharDevice

        - name: gluetun-config
          persistentVolumeClaim:
            claimName: gluetun-pvc

        - name: config
          persistentVolumeClaim:
            claimName: config-pvc
        - name: downloads
          persistentVolumeClaim:
            claimName: downloads-pvc
        - name: files
          persistentVolumeClaim:
            claimName: files-pvc
        - name: output
          persistentVolumeClaim:
            claimName: output-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: qbittorrent
  namespace: qbittorrent
spec:
  selector:
    app: qbittorrent
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  type: ClusterIP
