apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vaultwarden
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/cpeluti/homelab.git'
    path: custom/vaultwarden
    targetRevision: main
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: vaultwarden
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true