apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openbao
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/cpeluti/homelab.git'
    path: custom/openbao
    targetRevision: main
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: openbao
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true