---
apiVersion: v1
kind: Namespace
metadata:
  name: gluetun
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: gluetun-secrets
  namespace: gluetun
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: openbao-store
    kind: ClusterSecretStore
  target:
    creationPolicy: Owner
  data:
  - secretKey: vpn-token
    remoteRef:
      key: gluetun
      property: vpn-token
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gluetun
  namespace: gluetun
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gluetun
  template:
    metadata:
      labels:
        app: gluetun
    spec:
      containers:
        - name: gluetun
          image: qmcgaw/gluetun:latest
          env:
            - name: VPN_SERVICE_PROVIDER
              value: "protonvpn"
            - name: VPN_TYPE
              value: "wireguard"
            - name: WIREGUARD_PRIVATE_KEY
              valueFrom:
                secretKeyRef:
                  name: gluetun
                  key: vpn-token
            - name: SERVER_COUNTRIES
              value: "United Kingdom"
            - name: SERVER_CITIES
              value: "London"
            - name: VPN_PORT_FORWARDING
              value: "on"
            - name: HTTP_CONTROL_SERVER_AUTH_DEFAULT_ROLE
              value: '{"auth":"none"}'
          ports:
            - containerPort: 8080 # se quiser expor API
          securityContext:
            capabilities:
              add: ["NET_ADMIN"]
---
apiVersion: v1
kind: Service
metadata:
  name: gluetun
  namespace: gluetun
spec:
  selector:
    app: gluetun
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080