kind: Namespace
apiVersion: v1
metadata:
  name: openbao
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name:  openbao
  namespace: openbao
  labels:
    app:  openbao
spec:
  selector:
    matchLabels:
      app: openbao
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app:  openbao
    spec:
      # initContainers:
        # Init containers are exactly like regular containers, except:
          # - Init containers always run to completion.
          # - Each init container must complete successfully before the next one starts.
      containers:
      - name:  openbao
        image:  openbao/server:latest
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 100m
            memory: 100Mi
        env:
        - name: DOMAIN
          valueFrom:
            secretKeyRef:
              name: openbao-domain   # nome do Secret
              key: VW_DOMAIN
        ports:
        - containerPort:  80
          name:  openbao
        volumeMounts:
        - name: data
          mountPath: /data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: openbao-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: openbao-svc
  namespace: openbao
spec:
  selector:
    app: openbao
  ports:
    - name: http
      protocol: TCP
      port: 8000
      targetPort: 80
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: openbao-pv
spec:
  storageClassName: "openbao"
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /var/openbao
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: openbao-pvc
  namespace: openbao
spec:
  storageClassName: "openbao"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  volumeName: openbao-pv
