kind: Namespace
apiVersion: v1
metadata:
  name: vaultwarden
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: vaultwarden
  namespace: vaultwarden
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: openbao-store
    kind: ClusterSecretStore
  target:
    creationPolicy: Owner
  data:
    - secretKey: ddns-token
      remoteRef:
        key: vaultwarden
        property: domain
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name:  vaultwarden
  namespace: vaultwarden
  labels:
    app:  vaultwarden
spec:
  selector:
    matchLabels:
      app: vaultwarden
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app:  vaultwarden
    spec:
      # initContainers:
        # Init containers are exactly like regular containers, except:
          # - Init containers always run to completion.
          # - Each init container must complete successfully before the next one starts.
      containers:
      - name:  vaultwarden
        image:  vaultwarden/server:latest
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 100m
            memory: 100Mi
        env:
        - name: DOMAIN
          valueFrom:
            secretKeyRef:
              name: vaultwarden
              key: domain
        ports:
        - containerPort:  80
          name:  vaultwarden
        volumeMounts:
        - name: data
          mountPath: /data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: vaultwarden-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: vaultwarden-svc
  namespace: vaultwarden
spec:
  selector:
    app: vaultwarden
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: vaultwarden-pv
spec:
  storageClassName: "vaultwarden"
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /var/vaultwarden
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vaultwarden-pvc
  namespace: vaultwarden
spec:
  storageClassName: "vaultwarden"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  volumeName: vaultwarden-pv
