apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-nginx
  namespace: argocd
spec:
  destination:
    namespace: ingress-nginx
    server: https://kubernetes.default.svc
  project: homelab
  source:
    chart: ingress-nginx  # Note: era plane-enterprise no comando helm
    repoURL: https://kubernetes.github.io/ingress-nginx
    targetRevision: 4.13.3
  syncPolicy:
    syncOptions:
      - ServerSideApply=true
      - CreateNamespace=true
    automated:
      allowEmpty: true
      prune: true
      selfHeal: true

    # Equivalente ao --wait e --wait-for-jobs
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m