kind: Namespace
apiVersion: v1
metadata:
  name: external-secrets
---
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: openbao-store
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  provider:
    vault:
      server: "http://openbao.openbao.svc.cluster.local:8200"
      path: "secret"
      auth:
        kubernetes:
          mountPath: "kubernetes"  # o caminho onde habilitamos o auth
          role: "external-secrets"
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets
  namespace: argocd
spec:
  destination:
    namespace: external-secrets
    server: https://kubernetes.default.svc
  project: homelab
  source:
    chart: external-secrets
    repoURL: https://charts.external-secrets.io
    targetRevision: 0.20.3
  syncPolicy:
    syncOptions:
      - ServerSideApply=true
    automated:
      allowEmpty: true
      prune: true
      selfHeal: true