apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: plane
  namespace: argocd
spec:
  destination:
    namespace: plane
    server: https://kubernetes.default.svc
  project: homelab
  source:
    chart: plane-ce  # Note: era plane-enterprise no comando helm
    repoURL: https://helm.plane.so/
    targetRevision: 1.3.1
    helm:
      parameters:
        - name: planeVersion
          value: "v1.0.0"
        - name: ingress.appHost
          value: "plane.marcodopercurso.com.br"
        - name: ingress.minioHost
          value: "plane-minio.marcodopercurso.com.br"
        - name: ingress.rabbitmqHost
          value: "plane-mq.marcodopercurso.com.br"
        - name: ingress.ingressClass
          value: "nginx"
        
      timeout: 10m
  
  syncPolicy:
    syncOptions:
      - ServerSideApply=true
      - CreateNamespace=true
    automated:
      allowEmpty: true
      prune: true
      selfHeal: true
    
    # Equivalente ao --wait e --wait-for-jobs
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m