---
kind: Namespace
apiVersion: v1
metadata:
  name: lidarr
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: lidarr
  namespace: lidarr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lidarr
  template:
    metadata:
      labels:
        app: lidarr
    spec:
      hostNetwork: true
      containers:
        - name: lidarr
          image: lscr.io/linuxserver/lidarr:latest
          ports:
            - name: http
              containerPort: 8686
              protocol: TCP
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: TORRENTING_PORT
              value: "45455"
            - name: TZ
              value: "Etc/UTC"
          volumeMounts:
            - name: config 
              mountPath: /config
            - name: downloads
              mountPath: /downloads
            - name: files 
              mountPath: /files
            - name: output 
              mountPath: /output
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "500m"
      volumes:
        - name: downloads
          persistentVolumeClaim:
            claimName: downloads-pvc
        - name: config
          persistentVolumeClaim:
            claimName: config-pvc
        - name: files
          persistentVolumeClaim:
            claimName: files-pvc
        - name: output
          persistentVolumeClaim:
            claimName: output-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: lidarr
  namespace: lidarr
spec:
  selector:
    app: lidarr
  ports:
  - name: http
    port: 8686
    targetPort: 8686
    protocol: TCP
  type: ClusterIP
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: lidarr-config-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /var/lidarr/config
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: lidarr-music-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /var/lidarr/music
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: lidarr-downloads-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /var/lidarr/downloads
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: music-pvc
  namespace: lidarr
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  volumeName: lidarr-music-pv
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: downloads-pvc
  namespace: lidarr
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  volumeName: lidarr-downloads-pv
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: config-pvc
  namespace: lidarr
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  volumeName: lidarr-config-pv



# ---

# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: qbittorrent-ingress
#   namespace: qbittorrent
#   annotations:
#     nginx.ingress.kubernetes.io/rewrite-target: /
# spec:
#   rules:
#     - http:
#         paths:
#           - path: /
#             pathType: Prefix
#             backend:
#               service:
#                 name: qbittorrent  # Nome do serviço do NGINX
#                 port:
#                   number: 8080  # Porta exposta pelo serviço NGINX
